# Generated by Django 5.2.11 on 2026-02-07 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allow_usage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allow_usage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WritingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allow_usage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_netid', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('check_in_date', models.DateTimeField(auto_now_add=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('program_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compass_visits.programarea')),
                ('tutoring_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compass_visits.tutoringoption')),
            ],
        ),
    ]
