# Generated by Django 5.2.11 on 2026-04-14 00:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allow_usage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allow_usage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WritingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allow_usage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_syskey', models.CharField(db_index=True, max_length=10)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('check_in_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('program_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compass_visits.programarea')),
                ('tutoring_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compass_visits.tutoringoption')),
                ('writing_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compass_visits.writingservice')),
            ],
        ),
    ]
