# Generated by Django 5.2.13 on 2026-06-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass_visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='student_netid',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
